# Site settings
title: WhaleTech
description: What was once here is now gone.
logo: whaletech.png
baseurl: "" # the subpath of your site, e.g. /blog/
url:

# Build settings
markdown: kramdown
highlighter: rouge
future: true

exclude:
 - Gemfile
 - Gemfile.lock

gems:
  - jekyll-gist
